### ISSUE TITLE
Update action from v1.2.0 in rossjrw

### ISSUE THREAD

**Issue by ccarouge** [ACCESS-NRI/pr-preview-action#3]
We need some update from rossjrw for the URL name, see [issue 163 in the Hive](https://github.com/ACCESS-Hive/access-hive.github.io/issues/163).

We still need this fork to allow previews to build from forks.

**Comment by aidanheerdegen** [comment]
Yes I didn't understand, so just reverted to the new v1.2 in upstream, which doesn't grok the PR parameter suff. I will pull in the changes to support GitHub organisation page naming convention and change back to this action.
